server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Required for nginx-prometheus-exporter to scrape metrics
    location /stub_status {
        stub_status on;
        allow 172.0.0.0/8;   # allow Docker internal network
        deny all;
    }
}
